name: Docker Image CI for main-micro-site

on:
  push:
    tags:
      - 'main-micro-site-v*'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: version
        run: echo ::set-output name=release_version::${GITHUB_REF#refs/*/}

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to aliyun Hub
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shenzhen.aliyuncs.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./packages/main-micro-site
          platforms: 
            linux/amd64
          push: true
          build-args: 
            APP_NAME=${{ github.event.repository.name }}
          tags: 
            registry.cn-shenzhen.aliyuncs.com/httpxyc/github:latest,registry.cn-shenzhen.aliyuncs.com/httpxyc/github:${{ steps.version.outputs.release_version }}
